apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace:
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlkybGtaWEoyWlc1dmJUcFVkamczS25oRGEwNUJZVUE3WFNJPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson